# This workflow doesn't support cache invalidation for unused dependencies at the moment

kind: pipeline
type: ssh
name: Run tests on M1

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

steps:
  - name: Update rust
    commands:
      - /usr/local/bin/rustup-update
  - name: Run tests
    environment:
      SRCENV:
        from_secret: srcenv
      CARGO_HOME:
        from_secret: cargohome
      CARGO_TARGET_DIR:
        from_secret: cargotarget
    commands:
      - source $SRCENV/.cargo/env
      - export RUSTUP_HOME=$SRCENV/.rustup
      - cargo run -p skyd -- --nosave &
      - cargo test -- --test-threads=1
  - name: Stop skyd
    commands:
      - pkill skyd
