[package]
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
build = "build.rs"
description = "Skytable is a free and open-source realtime NoSQL database"
edition = "2018"
license = "AGPL-3.0"
name = "skyd"
version = "0.6.2"

[dependencies]
# internal deps
skytable = {git = "https://github.com/skytable/client-rust", branch = "next", default-features = false}
# external deps
bincode = "1.3.3"
bytes = "1.0.1"
chrono = "0.4.19"
clap = {version = "2.33.3", features = ["yaml"]}
dashmap = {version = "4.0.2", features = ["serde"]}
env_logger = "0.8.4"
lazy_static = "1.4.0"
libsky = {path = "../libsky"}
log = "0.4.14"
openssl = {version = "0.10.34", features = ["vendored"]}
parking_lot = "0.11.1"
regex = "1.5.4"
serde = {version = "1.0.126", features = ["derive"]}
tokio = {version = "1.7.0", features = ["full"]}
tokio-openssl = "0.6.1"
toml = "0.5.8"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
# external deps
jemallocator = "0.3.2"
[target.'cfg(target_os = "windows")'.dependencies]
# external deps
winapi = {version = "0.3.9", features = ["fileapi"]}

[target.'cfg(unix)'.build-dependencies]
# external deps
cc = "1.0.68"

[dev-dependencies]
# internal deps
sky_macros = {path = "../sky-macros"}
skytable = {git = "https://github.com/skytable/client-rust", features = ["async"], default-features = false, branch = "next"}
# external deps
tokio = {version = "1.6.1", features = ["test-util"]}

[target.'cfg(unix)'.dependencies]
# external deps
libc = "0.2.96"

[package.metadata.deb]
assets = [
  ["../target/release/skysh", "usr/bin/", "755"],
  ["../target/release/skyd", "usr/bin/", "755"],
  ["../target/release/sky-bench", "usr/bin/", "755"],
]
copyright = "2021, Sayan Nandan <nandansayan@outlook.com>"
depends = "$auto"
extended-description = """\
Skytable is a free and open-source realtime NoSQL database, designed from the ground up that
aims to provide flexibility in data modeling without compromising on performance or scalability"""
license-file = ["../LICENSE", "0"]
maintainer = "Sayan Nandan <nandansayan@outlook.com>"
maintainer-scripts = "debian/"
name = "skytable"
priority = "optional"
section = "database"
systemd-units = {enable = true }
